//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreMSDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Item
    {
        public int ItemID { get; set; }

        [Required(ErrorMessage = "Username is required.")]
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string ItemType { get; set; }

        [Required(ErrorMessage = "Username is required.")]
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> TDate { get; set; }
    }
}
